### ISSUE TITLE
New interface, timed like & other stuffs

### ISSUE THREAD

**Issue by Taknok** [austencm/youtube-auto-like#17]
Hi,

Mainly 3 points here 😃 :
- I just see that you change the option interface by separating "disable" with a checkbox. I had the same idea but always stayed as dead code ^^. This idea is related to point 2.
- I also see that you added timed like. I was wondering why 50% or 2 min only ? On my repo I added a version allowing the user to choose the percentage of video or the time. Why did you chose to fix this setting ? Also writing the timed code, I was wondering : this force the user to select "subs like" or "all like", but with custom separated timers users could choose to set instant liker on subs videos and a 100% liker on other videos. For that I thought to add section instead named instant liker etc. What do you think of this ?
- I added in my repo more check and code to prevent multiple runs that happened on Firefox (I don't know if Chrome was affected too). I also prepare the code to add youtube tv support like requested in #15 .
Here are the draw that I tried (the check box is animated with the check progressively showing like hand wrote and red/green for desactivated/activated.
![image](https://user-images.githubusercontent.com/12498020/45191350-facb1900-b242-11e8-95f9-765c5fb7ac94.png)
open section :
![image](https://user-images.githubusercontent.com/12498020/45191361-0cacbc00-b243-11e8-8278-2f21368a6f3e.png)

**Comment by austencm** [comment]
@Taknok Thanks for the input! 

Re: your second point, I definitely think allowing the user to set their own percentage/duration would be an improvement. I haven't added it because I haven't seen any requests for it. I don't have a lot of time to work on extensions right now so I try to prioritize new stuff based on interest. I'll make a separate issue for this and see if anyone chimes in.

It's been a little while since I've tested but I think I do recall multiple runs happening at some point. I'll take a look at your repo. Edge cases have been tricky to nail down with this extension. I'm glad I had the 50% like option running for a while before publishing because the first iteration didn't account for ads :/.

YouTube TV support would be great. I've never heard about it until #15. Seems like it should be doable.

Nice checkbox. Maybe I'll co-opt it.
