### ISSUE TITLE
The Auto-Like doesn't add to the like count.

### ISSUE THREAD

**Issue by MCM-Math** [austencm/youtube-auto-like#80]
I get the standard message that the video has been added to my Liked videos, but it doesn't add the like to the like count.  I can even click on the Like button to add to the like count for the video, even after the Auto-Like supposedly kicked in.

**Comment by austencm** [comment]
@MCM-Math if you refresh the page, is the video liked?

**Comment by MCM-Math** [comment]
Looks like it is.  I guess its a visual glitch, but the actual liking seems to work.

**Comment by Taknok** [comment]
Maybe no useful because I'm speaking for Firefox behavior.

They changed recently the layout (again), the like append: the popup is shown on bottom left, but the button is not colored. The like percentage bar will be colored when liking.

This is due because yt add *-computed in their code. The code of the addon select the first occurence of the like button for the video, which is in the 1st underline section. Clicking on this buttton trigger the event of like but not the JS to color the button. Clicking on the button in the computed section color the button.
![image](https://user-images.githubusercontent.com/12498020/119261642-9f027300-bbd8-11eb-9990-1739f2d79185.png)

[2.3.6](https://github.com/Taknok/youtube-auto-like/commit/1302983fb2f74df31c815eaede52b4c53b20f094) on Firefox is released to fix this behavior.

**Comment by austencm** [comment]
I noticed that too, thanks for the fix @Taknok 🙏🏻
New release coming today.

**Comment by MCM-Math** [comment]
The latest version seems to work fully now.
