### ISSUE TITLE
Add selector for new like button variant

### ISSUE THREAD

**Issue by Kinomora** [austencm/youtube-auto-like#95]
Seems that youtube/google has broken this extension again. I thought it was a mistake at first but I'm certain now that it's not working anymore.
Version 2.7.1
Chrome 96.0.4664.110

**Comment by Taknok** [comment]
@austencm : here is the commit done for Firefox, may be relevant (or not ^^) for Chrome.
https://github.com/Taknok/youtube-auto-like/commit/ea47f31037ef4277683b410f8a4b79cdce96d726

**Comment by wthueb** [comment]
YouTube appears to be testing a new like button design that uses `tp-yt-paper-button` instead of `yt-icon-button`, otherwise the selector is still the same.

@austencm Do you have an aversion to slightly modifying the code to allow for multiple different selectors for the buttons, that way a fix could be implemented for this even though not all people will have the same selectors? Simply changing `selectors.likeButton` (and others) to arrays and iterating through them until you find a match seems like it wouldn't be a horrible idea.

**Comment by austencm** [comment]
I'm hoping to put up a new version this weekend. Can definitely include this.

**Comment by Kinomora** [comment]
Is there a new release for this yet?
